### ISSUE TITLE
Fix module not found './images/logo.svg' in Navbar component

### ISSUE THREAD

**Issue by AlexGarrixen** [leave20/store#2]

**Comment by leave20** [comment]
Lo has solucionado? para verlo mañana a primera hora

**Comment by AlexGarrixen** [comment]
La solucion seria crear la carpeta con el el archivo correspondiente(logo) en la ruta que esta especificada(dentro de la carpeta src).

![fix stacklicode](https://user-images.githubusercontent.com/60531551/116354943-bd827380-a7be-11eb-8848-26b67c32a79f.png)

Otra solucion seria guardar el logo en la carpeta public y accederlo de esta forma:
process.env.PUBLIC_URL + '/path/resource

**Comment by leave20** [comment]
te doy luz verde para que hagas el cambio , escoge cualquiera de las dos opciones
